backend:
  name: git-gateway
  branch: main

media_folder: 'public/images/uploads'
public_folder: 'images/uploads'

collections:
  - name: 'diner'
    label: 'Diner'
    folder: 'src/pages/diner'
    create: true,
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: '../layouts/Recipe.astro' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
