backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: 'public/images/uploads'
public_folder: 'images/uploads'

collections:
  - name: 'diner'
    label: 'Diner'
    folder: 'src/pages/diner'
    create: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'src/layouts/Recipe.astro' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }